#!/usr/bin/env bash

set -e

CONFIG_FILE_PATH=$1

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

SESSION_NAME="RUNNER__$(date +%F_%H-%M-%S)"

tmux new-session -d -s ${SESSION_NAME}
tmux send-keys -t ${SESSION_NAME}:.0 'echo "This window is the service runner..."' Enter

tmux split-window -v

tmux send-keys -t ${SESSION_NAME}:.1 "python3 ${SCRIPT_DIR}/src/Runner.py ${SESSION_NAME} ${CONFIG_FILE_PATH}" Enter

# select python pane
tmux select-pane -t ${SESSION_NAME}:.1
tmux -2 attach-session -d